version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    hostname: nginx-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/etc/nginx/certs:/etc/nginx/certs
      - ./volumes/etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/usr/share/nginx/html:/usr/share/nginx/html
      - ./custom.conf:/etc/nginx/conf.d/custom.conf:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - public

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    environment:
      - DEFAULT_EMAIL=me@andreas-sk.de
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/etc/nginx/certs:/etc/nginx/certs
      - ./volumes/etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/usr/share/nginx/html:/usr/share/nginx/html
    networks:
      - public

networks:
  public:
    name: public
