version: "3.7"
services:
  ocis:
    image: owncloud/ocis:1.14.0
    restart: always
    entrypoint:
      - /bin/sh
      - /entrypoint.sh
    environment:
      LOG_LEVEL: info
      PROXY_TLS: "false"
      OCIS_URL: https://ocis.andreas-sk.de
      OCIS_JWT_SECRET: ${OCIS_JWT_SECRET}
      OCIS_TRANSFER_SECRET: ${OCIS_TRANSFER_SECRET}
      OCIS_MACHINE_AUTH_API_KEY: ${OCIS_MACHINE_AUTH_API_KEY}
      IDP_LDAP_BIND_PASSWORD: ${IDP_LDAP_BIND_PASSWORD}
      IDP_ACCESS_TOKEN_EXPIRATION: 86400 # 24h
      IDP_ID_TOKEN_EXPIRATION: 86400 # 24h
      STORAGE_LDAP_BIND_PASSWORD: ${STORAGE_LDAP_BIND_PASSWORD}
      STORAGE_HOME_DRIVER: s3ng
      STORAGE_USERS_DRIVER: s3ng
      STORAGE_METADATA_DRIVER: ocis # keep metadata on ocis storage since this are only small files atm
      # s3ng specific settings
      STORAGE_USERS_DRIVER_S3NG_ENDPOINT: https://s3.eu-central-003.backblazeb2.com
      STORAGE_USERS_DRIVER_S3NG_REGION: eu-central-003
      STORAGE_USERS_DRIVER_S3NG_ACCESS_KEY: ${OCIS_S3_ACCESS_KEY}
      STORAGE_USERS_DRIVER_S3NG_SECRET_KEY: ${OCIS_S3_SECRET_KEY}
      STORAGE_USERS_DRIVER_S3NG_BUCKET: ${OCIS_S3_BUCKET}
      # Storage Frontend
      STORAGE_FRONTEND_UPLOAD_MAX_CHUNK_SIZE: 100000000 # <100MB
    volumes:
      - ./volumes/ocis:/var/lib/ocis
      - ./entrypoint.sh:/entrypoint.sh
    labels:
      traefik.enable: "true"
      traefik.http.routers.ocis.rule: "Host(`ocis.andreas-sk.de`)"
      traefik.http.services.ocis.loadbalancer.server.port: 9200
      traefik.http.routers.ocis.tls: "true"
      traefik.http.routers.ocis.tls.certresolver: letsencrypt
      #traefik.http.routers.ocis.middlewares: whitelist-home@docker
      traefik.http.middlewares.whitelist-home.ipwhitelist.sourcerange: ${HOME_IP}
    networks:
      - public
    logging:
      driver: local

networks:
  public:
    name: public
