- hosts: all
  tasks:
  - name: Create flarum directory
    file:
      path: /docker/flarum
      state: directory
      owner: ubuntu
    become: true
  - name: Upload all files
    copy:
      src: files/flarum/{{ item }}
      dest: /docker/flarum
    with_items:
      - docker-compose.yml
      - flarum.env
      - nginx.conf
  - name: Start up Flarum docker-compose 
    command: docker-compose up -d
    become: yes
    args:
      chdir: /docker/flarum
    environment:
      FLARUM_MYSQL_ROOT_PASSWORD: "{{ lookup('env','FLARUM_MYSQL_ROOT_PASSWORD') }}"
      FLARUM_MYSQL_PASSWORD: "{{ lookup('env','FLARUM_MYSQL_PASSWORD') }}"
  - name: Install extensions
    command: docker exec -it flarum extension require {{ item }}
    become: yes
    with_items:
      - fof/upload
      - fof/pages
      - fof/reactions
      - fof/user-directory
      - fof/follow-tags
      - fof/gamification
      - fof/default-group
