- hosts: all
  tasks:
  - name: Create flarum_rehearse directory
    file:
      path: /docker/flarum_rehearse
      state: directory
      owner: ubuntu
    become: true

  - name: Upload all files
    copy:
      src: files/flarum_rehearse/{{ item }}
      dest: /docker/flarum_rehearse
    with_items:
      - docker-compose.yml
      - flarum.env
      - nginx.conf
      - composer.repositories.txt

  - name: Template composer/auth.json
    template:
      src: files/flarum_rehearse/composer_auth.json
      dest: /docker/flarum_rehearse/composer_auth.json

  - name: Start up Flarum Rehearse docker-compose 
    command: docker-compose up -d
    become: yes
    args:
      chdir: /docker/flarum_rehearse
    environment:
      FLARUM_REHEARSE_MYSQL_ROOT_PASSWORD: "{{ lookup('env','FLARUM_REHEARSE_MYSQL_ROOT_PASSWORD') }}"
      FLARUM_REHEARSE_MYSQL_PASSWORD: "{{ lookup('env','FLARUM_REHEARSE_MYSQL_PASSWORD') }}"

  - name: Install extensions
    command: docker exec -it flarum_rehearse extension require {{ item }}
    become: yes
    with_items:
      - fof/upload
      - fof/pages
      - fof/reactions
      - fof/user-directory
      - fof/follow-tags
      - fof/gamification
      - fof/default-group
