- hosts: all
  tasks:
  - name: Create Nextcloud directory
    file:
      path: /docker/nextcloud
      state: directory
      owner: ubuntu
    become: true
  - name: Upload all files
    copy:
      src: files/nextcloud/{{ item }}
      dest: /docker/nextcloud
    with_items:
      - docker-compose.yml
      - nginx.conf
      - www.conf
  - name: Start up Nextcloud docker-compose 
    command: docker-compose up -d
    become: yes
    args:
      chdir: /docker/nextcloud
    environment:
      NEXTCLOUD_MYSQL_ROOT_PASSWORD: "{{ lookup('env','NEXTCLOUD_MYSQL_ROOT_PASSWORD') }}"
      NEXTCLOUD_MYSQL_PASSWORD: "{{ lookup('env','NEXTCLOUD_MYSQL_PASSWORD') }}"
      NEXTCLOUD_OBJECTSTORE_S3_BUCKET: "{{ lookup('env','NEXTCLOUD_OBJECTSTORE_S3_BUCKET') }}"
      NEXTCLOUD_OBJECTSTORE_S3_KEY: "{{ lookup('env','NEXTCLOUD_OBJECTSTORE_S3_KEY') }}"
      NEXTCLOUD_OBJECTSTORE_S3_SECRET: "{{ lookup('env','NEXTCLOUD_OBJECTSTORE_S3_SECRET') }}"
      
