- hosts: all
  tasks:
  - name: Create ocis directory
    file:
      path: /docker/ocis
      state: directory
      owner: ubuntu
    become: true

  - name: Upload all files
    copy:
      src: files/ocis/{{ item }}
      dest: /docker/ocis
    with_items:
      - docker-compose.yml
      - entrypoint.sh

  - name: Start up ocis docker-compose 
    command: docker-compose up -d
    become: yes
    args:
      chdir: /docker/ocis
    environment:
      HOME_IP: "{{ lookup('env','HOME_IP') }}"
      OCIS_S3_ACCESS_KEY: "{{ lookup('env','OCIS_S3_ACCESS_KEY') }}"
      OCIS_S3_SECRET_KEY: "{{ lookup('env','OCIS_S3_SECRET_KEY') }}"
      OCIS_S3_BUCKET: "{{ lookup('env','OCIS_S3_BUCKET') }}"
      IDP_LDAP_BIND_PASSWORD: "{{ lookup('env','IDP_LDAP_BIND_PASSWORD') }}"
      STORAGE_LDAP_BIND_PASSWORD: "{{ lookup('env','STORAGE_LDAP_BIND_PASSWORD') }}"
      OCIS_JWT_SECRET: "{{ lookup('env','OCIS_JWT_SECRET') }}"
      OCIS_TRANSFER_SECRET: "{{ lookup('env', 'OCIS_TRANSFER_SECRET') }}"
