- hosts: all
  tasks:
  - name: Create System directory
    file:
      path: /docker/system
      state: directory
      owner: ubuntu
    become: true

  - name: Upload all files
    copy:
      src: files/system/{{ item }}
      dest: /docker/system
    with_items:
      - docker-compose.yml
    register: files_upload
  
  - name: Template admin_auth.txt
    template:
      src: files/system/admin_auth
      dest: /docker/system/admin_auth
    register: admin_auth_upload

  - name: Template traefik.yml
    template:
      src: files/system/traefik.yml
      dest: /docker/system/traefik.yml
    register: traefik_yml_upload

  - name: Start up System docker-compose 
    command: docker-compose up -d
    become: true
    args:
      chdir: /docker/system
    environment:
      INFLUXDB_INFLUXDB_USER_PASSWORD: "{{ lookup('env','INFLUXDB_INFLUXDB_USER_PASSWORD') }}"

  - name: Restart System docker-compose
    command: docker-compose restart
    become: true
    args:
      chdir: /docker/system
    when: files_upload.changed or admin_auth_upload.changed or traefik_yml_upload
    
  - name: Clean up Docker
    command: docker system prune -af
    become: true
