- hosts: all
  tasks:
  - name: Create System directory
    file:
      path: /docker/system
      state: directory
      owner: ubuntu
    become: true

  - name: Upload all files
    copy:
      src: files/system/{{ item }}
      dest: /docker/system
    with_items:
      - docker-compose.yml
      - traefik.yml
  
  - name: Template admin_auth.txt
    template:
      src: files/system/admin_auth
      dest: /docker/system/admin_auth

  - name: Start up System docker-compose 
    command: docker-compose up -d
    become: true
    args:
      chdir: /docker/system
    environment:
      INFLUXDB_INFLUXDB_USER_PASSWORD: "{{ lookup('env','INFLUXDB_INFLUXDB_USER_PASSWORD') }}"
