version: '3.8'

services:
  telegraf:
    image: telegraf:1.18-alpine
    restart: always
    environment:
      - INFLUXDB_DB=monitoring
      - INFLUXDB_USER=monitoring
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_INFLUXDB_USER_PASSWORD}
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring
      - public
    logging:
      driver: local

  influxdb:
    image: influxdb:1.8-alpine
    hostname: influxdb
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_DB=monitoring
      - INFLUXDB_USER=monitoring
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_INFLUXDB_USER_PASSWORD}
      - INFLUXD_LOG_LEVEL=error
    volumes:
      - ./volumes/influxdb/var/lib/influxdb:/var/lib/influxdb
    networks:
      - monitoring
    logging:
      driver: local

  grafana:
    image: grafana/grafana:7.5.5
    hostname: grafana
    container_name: grafana
    restart: always
    environment:
      - INFLUXDB_DB=monitoring
      - INFLUXDB_USER=monitoring
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_INFLUXDB_USER_PASSWORD}
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./server-dashboard.json:/etc/grafana/provisioning/dashboards/server-dashboard.json:ro
      - ./volumes/grafana/var/lib/grafana:/var/lib/grafana
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: Host(`monitoring.andreas-sk.de`)
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.tls.certresolver: letsencrypt
    networks:
      - public
      - monitoring
    logging:
      driver: local

networks:
  monitoring:
    name: monitoring
  public:
    name: public
