version: "3.8"

services:
  ofelia:
    image: mcuadros/ofelia:v0.3.0
    container_name: ofelia
    command: daemon --docker
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: local
