version: "3.8"

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: always
    environment:
      - TRAEFIK_METRICS_INFLUXDB_PASSWORD=${INFLUXDB_INFLUXDB_USER_PASSWORD}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./volumes/traefik/acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
      - monitoring

  ofelia:
    image: mcuadros/ofelia:v0.3.0
    container_name: ofelia
    command: daemon --docker
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: local

networks:
  public:
    name: public
  monitoring:
    name: monitoring
