providers:
  docker:
    exposedByDefault: false
    network: public

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: me@andreas-sk.de
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

metrics:
  influxDB:
    address: influxdb:8086
    protocol: http
    database: monitoring
    username: monitoring

api:
  dashboard: true

pilot:
  token: "{{ lookup('env','TRAEFIK_PILOT_TOKEN') }}"

experimental:
  plugins:
    blockpath:
      moduleName: "github.com/traefik/plugin-blockpath"
      version: "v0.2.1"
